### ISSUE TITLE
Resolve oscm-common duplication

### ISSUE THREAD

**Issue by kowalczyka** [servicecatalog/oscm-app#18]
**Summary**
oscm-common is used as a dependency both in oscm and oscm-app repository. This must be handled so that no to support in both repositories.

**Details**
Possible solutions would be:
a) move oscm-common to other repo and use jitpack for handling dependencies, or
b) extract crucial (used) parts out of the oscm-common into separate module/class/method (in oscm-app)

**Acceptance criteria**
oscm-common is handled and developed only in one repository

**Additional context**
N/A

**Comment by GoebelL** [comment]
Let's go for solution a).
