### ISSUE TITLE
Improve unit test coverage

### ISSUE THREAD

**Issue by kowalczyka** [servicecatalog/oscm-app#21]
**Summary**
After migration to maven it turned out that the unit tests coverage is low. This must be increased.

**Details**
Many of classes were never unit tested. Some of unit tests where switched off because of dependency  to some common test base module no longer existing in this repo.

**Acceptance criteria**
- [ ] Code coverage should be around 60% 

**Additional context**
N/A

**Comment by cworf91** [comment]
https://github.com/servicecatalog/oscm-app/pull/98

**Comment by GoebelL** [comment]
Done.
