### ISSUE TITLE
Missing build label

### ISSUE THREAD

**Issue by GoebelL** [servicecatalog/oscm-app#24]
**Version Info**
Private build from 2019/06/12 

**Describe the bug**
This is occuring since APP source code has been moved to a separate repository. It is due the fact, that the maven job is not adding build labels in the metainfo of the respective controller application bundles. 
Consequently a wrong and incomplete version information is shown in the about dialog in all controller UIs.  

**How to Reproduce**
1. Login to OpenStack controller UI at https://FQDN:8881/oscm-app-openstack/
2. Click on logo 'Open Service Catalog Manager'
3. Notice version info

**Observed behavior**
![grafik](https://user-images.githubusercontent.com/14805690/59370243-65fdca80-8d42-11e9-96f0-6992160209c9.png)
Note that the build label shows "-1" 

**Expected behavior**
Same as for oscm-portal:
![grafik](https://user-images.githubusercontent.com/14805690/59370389-b117dd80-8d42-11e9-8320-e9414e8cb184.png)

**Screenshots**
See above.

**Additional context**
N/A

**Comment by elfriedegoetz** [comment]
tested ok with Build 18.06.2019
