### ISSUE TITLE
Add eclipse configuration

### ISSUE THREAD

**Issue by GoebelL** [servicecatalog/oscm-app#26]
**Summary**
Add required meta files to get maven modules compiling after importing in an eclipse workspace and fix pom dependencies.

**Details**
Proposed steps
- [ ] Convert oscm-app as eclipse M2 project (choose Configure > Convert to Maven Project from context menu).
- [ ] Fix classpath dependencies, if requried 
- [ ] Add source code reference in .classpath for all classes imported from oscm-interfaces 
- [ ] Fix missing artifacts in POMs*
- [ ] Adpat gitignore file to include IDE settings

**Acceptance criteria**
After importing in eclipse all module clases are compiled straight away and without error markers. 

**Additional context**
*) Missing artifact:
![grafik](https://user-images.githubusercontent.com/14805690/59752866-46572c80-9283-11e9-9c05-7324a20ac3a9.png)

**Comment by GoebelL** [comment]
Group Id and Version information are correct with POM files on Jitpack.
I propose to align the local POM files that are contained in oscm-app and sub modules accordingly.
General speaking, we use and support lastest versions only. Therefore always refer to master-SNAPSHOT.

I suggest, for every module check and download the POM file content
```
https://javadoc.jitpack.io/com/github/servicecatalog/oscm-app/module-name/master-SNAPSHOT/module-name-master-SNAPSHOT.pom
```

Where &lt;**module-name**&gt; is oscm-app-common, oscm-app-ear, oscm-app-openstack... etc.

Example check this POM:
https://javadoc.jitpack.io/com/github/servicecatalog/oscm-app/oscm-app-common/master-SNAPSHOT/oscm-app-common-master-SNAPSHOT.pom
```
<parent>
   <groupId>com.github.servicecatalog.oscm-app</groupId>
   <artifactId>new-oscm-app</artifactId>
   <version>master-SNAPSHOT</version>
</parent>
<groupId>com.github.servicecatalog.oscm-app</groupId>
<artifactId>oscm-app-sample</artifactId>
<version>master-SNAPSHOT</version>
```

**Comment by GoebelL** [comment]
@cworf91 
Please raise a PR from your workspace fix.

**Comment by cworf91** [comment]
https://github.com/servicecatalog/oscm-app/pull/27
