### ISSUE TITLE
Test Connection results in an Error

### ISSUE THREAD

**Issue by elfriedegoetz** [servicecatalog/oscm-app#28]
**Version Info**
PRIVATE-BUILD-ON-18c04074cb562019/06/18

**Describe the bug**
test connection for vm-ware returns error if password is wrong for vSphere 

**How to Reproduce**
1. login to ocsm-app
2. Click on Test Connection from ess.vmware

**Observed behavior**
![app2](https://user-images.githubusercontent.com/15209605/60085255-3d5dd380-9739-11e9-894d-4d96d73f4289.PNG)

**Expected behavior**
helpful error massage

**Comment by cworf91** [comment]
https://github.com/servicecatalog/oscm-app/pull/39
