### ISSUE TITLE
app does not show all configured controllers

### ISSUE THREAD

**Issue by elfriedegoetz** [servicecatalog/oscm-app#29]
**Version Info**
PRIVATE-BUILD-ON-18c04074cb562019/06/18

**Describe the bug**
AWS controller is configured and works fine but shows "not configured"

![app](https://user-images.githubusercontent.com/15209605/60086128-d6d9b500-973a-11e9-9d1c-0c8b62b49faa.PNG)

**Comment by GoebelL** [comment]
This feature is new in APP. Currently, VMware and OpenStack adapters support the test connection function. The others are not availble. The labels are a bit misleading here, but anyway I don't see much value having those disabled buttons here. 
Let's remove them for now.

**Comment by cworf91** [comment]
https://github.com/servicecatalog/oscm-app/pull/42
