### ISSUE TITLE
vmware controller database relation distributedvirtualswitch missing

### ISSUE THREAD

**Issue by elfriedegoetz** [servicecatalog/oscm-app#30]
**Version Info**
PRIVATE-BUILD-ON-18c04074cb562019/06/18

**Describe the bug**
subscribe to a vm-ware service results in an error, and stay in status pending.
The error occurs with/without IPPool parameter.

log file:
2019-06-25 10:27:14,880 [EjbTimerPool - 3] - INFO  - Invoking action 'inspectTaskResult' of state 'CREATING' for instance '1561458209858'
  18427 2019-06-25 10:27:29,897 [EjbTimerPool - 3] - INFO  - Invoking action 'inspectTaskResult' of state 'CREATING' for instance '1561458209858'
  18428 2019-06-25 10:27:44,881 [EjbTimerPool - 1] - INFO  - Invoking action 'configureVM' of state 'CONFIGURE' for instance '1561458209858'
  18429 2019-06-25 10:27:45,412 [EjbTimerPool - 1] - INFO  - reconfigureDisks() extend system disk space to 41943040 (Hard disk 1)
  18430 2019-06-25 10:27:45,422 [EjbTimerPool - 1] - ERROR - Failed to retrieve ippools for DistributedVirtualSwitch esscluster
  18431 org.postgresql.util.PSQLException: ERROR: relation "distributedvirtualswitch" does not exist
  18432   Position: 42
  18433         at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2182)
  18434         at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1911)
  18435         at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:173)
  18436         at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:645)
  18437         at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:495)
  18438         at org.postgresql.jdbc2.AbstractJdbc2Statement.executeQuery(AbstractJdbc2Statement.java:380)
  18439         at sun.reflect.GeneratedMethodAccessor153.invoke(Unknown Source)

**Comment by cworf91** [comment]
https://github.com/servicecatalog/oscm-app/pull/33

**Comment by GoebelL** [comment]
@cworf91 
The PR is merged. Anything else or will you close this issue?

**Comment by elfriedegoetz** [comment]
tested okay with PRIVATE-BUILD-ON-20B07902D6082019/07/09
