### ISSUE TITLE
Rollback parameters

### ISSUE THREAD

**Issue by StavrevaS** [servicecatalog/oscm-app#4]
In the org.oscm.app.domain.ServiceInstance class there is a parameter rollback logic.
I suspect that there is a problem there because of improper method usage.

Please check the method 

```
  private void rollbackInstanceParameters(
            Properties rollbackInstanceParameters, EntityManager em)
            throws BadResultException {

        HashMap<String, Setting> rollbackParams = new HashMap<>();

        for (String name : rollbackInstanceParameters.stringPropertyNames()) {
            rollbackParams.put(name, new Setting(name,
                    rollbackInstanceParameters.getProperty(name)));
        }
        this.removeParams(rollbackParams, em);
        this.setInstanceParameters(rollbackParams);
        this.setRollbackParameters(null);

    }

```

After introducing the rollback of attributes the values in the properties are not strings anymore, but objects of type Setting. The method rollbackInstanceParameters.stringPropertyNames() returns only the properties keys if the key AND value are of type String. So I would expect here that we always get empty set.

The same is valid for rollbackInstanceAttributes method.

**Comment by GoebelL** [comment]
This issue was moved to servicecatalog/development#892
