### ISSUE TITLE
Basic authentication credentials not verified

### ISSUE THREAD

**Issue by kowalczyka** [servicecatalog/oscm-app#50]
**Version Info**
Latest

**Describe the bug**
When user authenticate to oscm-app in OIDC mode, credentials he entered are not being taken into account.

**How to Reproduce**
1. Go to oscm-app main page
2. Enter any credentials to basic authentication form

**Observed behavior**
User is successfully authenticated.

**Expected behavior**
User should not be succesfully authenticated.

**Screenshots**
If applicable, screenshots to help explain your problem.

**Additional context**
User credentials are also stored in DB - these are used for WS authentication. The credentials given via UI should be verified and checked againts these stored in DB.

**Comment by GoebelL** [comment]
@kowalczyka 
Binding for given credentials is required
https://github.com/servicecatalog/oscm-app/commit/2ac5902aef44f77c6b3344145b2c588693ec6af9#diff-9c4882a5a794cda00c711be94316e476L513

**Comment by GoebelL** [comment]
Related with #47
