### ISSUE TITLE
[Account] Manual provisioning adapter to support account creation for Crayon

### ISSUE THREAD

**Issue by GoebelL** [servicecatalog/oscm-app#61]
**Summary**
The request is to implement a simple provisioning adapter to support manual provisioning process steps for account creation in Crayon.

**Details**
The simple provisioning adapter shall be created on base of the sample controller which issues emails. The scope needs to be exentend to send out customizable emails to given recipients of registered OSCM users. This emails contain a completion link, by which the addressed users can complete the subscription instance.

**Acceptance criteria**
- [ ] Email texts are customizable with service parameter
- [ ] Email completion link lead to completing the subscription in OSCM
- [ ] Unit tests

**Additional context**
Maybe later

**Comment by cworf91** [comment]
https://github.com/servicecatalog/oscm-app/pull/68

**Comment by GoebelL** [comment]
@cworf91 Any update here?

**Comment by cworf91** [comment]
@GoebelL This PR can be merged after #68 is merged.
